[artifact]
folder = "build/libs"
pattern = "ensign-#.jar"
game_versions = ["1.21", "1.21.1"]
loaders = ["fabric", "quilt"]

[changelog]
type = "editor"

[modrinth]
id = "Roy1WHRz"
featured = true

[[modrinth.dependencies]]
id = "P7dR8mSH"
dependency_type = "required"

[[modrinth.dependencies]]
id = "ccKDOlHs"
dependency_type = "required"
